### ISSUE TITLE
Cell 0,0 only lists 2 mods

### ISSUE THREAD

**Issue by sparr** [thallada/modmapper-web#8]
The cell is red, which seems correct since most of its neighbors are orange/red with hundreds of mods affecting them. But clicking on it produces a count and list of just 2 mods.

![image](https://user-images.githubusercontent.com/121299/206885885-3ae7f740-bb11-4ac7-b443-02c2cdc5701b.png)

**Comment by thallada** [comment]
I finally fixed this. It took quite a while because I discovered an issue with interior cells in the process that required an upgrade of the database to fix and a lot of data cleanup.

Basically, this was happening because those two mods contained a Skyrim.esm plugin file that had cells at 0,0 but with different form IDs. I have no idea why they were doing that, but it was confusing the system. Modmapper will now only show edits to cells from the Skyrim.esm that ships with the game.
